require("rst.plugins-setup")
require("rst.core.options")
require("rst.core.keymaps")
require("rst.core.colorscheme")
require("rst.plugins.comment")
require("rst.plugins.nvim-tree")
require("rst.plugins.lualine")
require("rst.plugins.telescope")
require("rst.plugins.nvim-cmp")
require("rst.plugins.lsp.mason")
require("rst.plugins.lsp.lspconfig")
require("rst.plugins.lsp.null-ls")
require("rst.plugins.autopairs")
require("rst.plugins.treesitter")
require("rst.plugins.gitsigns")
require("rst.plugins.bufferline")
require("rst.plugins.which-key")
require("rst.plugins.dap")
vim.cmd("colorscheme everforest")
vim.cmd("highlight LspReferenceRead guibg='#888888'")
